# Generated by Django 3.0.8 on 2020-09-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200903_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='extra_info',
        ),
    ]
